EmbeddedStockAdmin/EmbeddedStockAdmin.Web/Controllers/NavigationController.cs
using EmbeddedStockAdmin.Domain.Abstract;
using EmbeddedStockAdmin.Web.Models;
using System.Web.Mvc;

namespace EmbeddedStockAdmin.Web.Controllers
{
    public class NavigationController : Controller
    {
        private IComponentRepository _componentRepo;

        public NavigationController(IComponentRepository componentRepo)
        {
            _componentRepo = componentRepo;
        }

        public PartialViewResult Menu()
        {
            return PartialView(_componentRepo.GetAllCategories());
        }

        [Authorize]
        [HttpPost]
        public ViewResult Search(string SearchString)
        {
            var componentmodels = _componentRepo.SearchComponentModels(SearchString);
            var summaryVM = ConvertHelpers.FromComponentModelsToSummaryVieModels(componentmodels, _componentRepo);
            return View(summaryVM);
        }
    }
}

EmbeddedStockAdmin/EmbeddedStockAdmin.Web/Views/Shared/_BaseLayout.cshtml
@{ 

}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div id="site">
        <div id="header">
            @Html.Partial("~/Views/Shared/_MenuBar.cshtml", null)
        </div>
        <div class="container">
            <div class="row panel">
                <div id="navigation" class="col-xs-3">
                    @Html.Partial("~/Views/Shared/_NavigationBar.cshtml")
                </div>
                <div id="content" class="col-xs-8">
                    @RenderBody()
                    @Html.Partial("~/Views/Shared/_Footer.cshtml", null)
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

EmbeddedStockAdmin/EmbeddedStockAdmin.Web/Views/Shared/_Footer.cshtml
<hr />
<footer>
    <p>&copy; @DateTime.Now.Year - Embedded Stock for Admin</p>
</footer>

EmbeddedStockAdmin/EmbeddedStockAdmin.Web/Views/Shared/_MenuBar.cshtml
<div class="navbar navbar-default navbar-fixed-top" style="margin-bottom: 10px">
    <div class="container">
        <div class="navbar-header">
            <img class="navbar-brand" alt="Embedded Stock" src="~/Images/au-logo.png">
            @Html.ActionLink("Embedded Stock", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <div class="col-sm-3 col-md-4">
                @using (Html.BeginForm("Search", "Navigation", FormMethod.Post, new { @class = "navbar-form", @role = "search" }))
                {
                    <div class="input-group">
                        @Html.TextBox("SearchString", null, new { @class = "form-control", @placeholder = "Search categories" })
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </div>
                }
            </div>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

EmbeddedStockAdmin/EmbeddedStockAdmin.Web/Views/Shared/_NavigationBar.cshtml
@*Category dropdown*@
<div class="btn-group-lg">
    @Html.ActionLink("Components", "Index", "Component", null, new { @class = "btn btn-block btn-default btn-lg" })
    <div class="btn-group-lg">
        <button type="button" class="btn btn-block btn-default btn-lg dropdown-toggle" data-toggle="dropdown" aria-haspopup="true">
            Category <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            @Html.Action("Menu", "Navigation")
        </ul>
    </div>
    @Html.ActionLink("Loaned components", "Loaned", "Component", null, new { @class = "btn btn-block btn-default btn-lg" })
</div>